name: ShoppingList
targets:
  ShoppingList:
    type: application
    platform: iOS
    deploymentTarget: &deployment_target "16.0"
    info:
      path: ShoppingList/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
    entitlements:
      path: ShoppingList/ShoppingList.entitlements
      properties:
        com.apple.security.application-groups: group.ShoppingList
    sources:
         - ShoppingList
    settings:
        base:
         ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
         ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
         CODE_SIGN_STYLE: Automatic
         DEVELOPMENT_ASSET_PATHS: "\"ShoppingList/Preview Content\""
         DEVELOPMENT_TEAM: 7RPFL7EXKD
         ENABLE_PREVIEWS: YES
         INFOPLIST_FILE: ShoppingList/Info.plist
         MARKETING_VERSION: &marketing_version 1.0.0
         CURRENT_PROJECT_VERSIO: 1
         PRODUCT_BUNDLE_IDENTIFIER: "masaharu.dobashi.ShoppingList"
         PRODUCT_NAME: "$(TARGET_NAME)"
    options:
        developmentLanguage: ja
    dependencies:
        - package: Realm
          product: RealmSwift
        
  ShoppingListTests:
      type: bundle.unit-test
      platform: iOS
      sources:
       - ShoppingListTests
      settings:
        base:
         ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
         BUNDLE_LOADER: "$(TEST_HOST)"
         CODE_SIGN_STYLE: Automatic
         DEVELOPMENT_TEAM: 7RPFL7EXKD
         INFOPLIST_FILE: ShoppingListTests/Info.plist
         PRODUCT_BUNDLE_IDENTIFIER: "masaharu.dobashi.ShoppingListTests"
         PRODUCT_NAME: "$(TARGET_NAME)"
         TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ShoppingList.app/ShoppingList"
      dependencies:
      - target: ShoppingList
        
        
  ShoppingListUITests:
      type: bundle.ui-testing
      platform: iOS
      sources:
        - ShoppingListUITests
      settings:
        base:
             ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
             CODE_SIGN_STYLE: Automatic
             DEVELOPMENT_TEAM: 7RPFL7EXKD
             INFOPLIST_FILE: ShoppingListUITests/Info.plist
             PRODUCT_BUNDLE_IDENTIFIER: "masaharu.dobashi.ShoppingListUITests"
             PRODUCT_NAME: "$(TARGET_NAME)"
             TEST_TARGET_NAME: ShoppingList
      dependencies:
       - target: ShoppingList
packages:
 XcodeGen:
    url: https://github.com/yonaskolb/XcodeGen
    version: 2.37.0
 Realm:
    url: https://github.com/realm/realm-swift
    version: 10.43.1
 R.swift:
    url: https://github.com/mac-cain13/R.swift
    version: 7.4.0


schemes:
  ShoppingList:
    build:
      targets:
        ShoppingList: all
        ShoppingListTests: [test]
        ShoppingListUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - ShoppingList
      targets:
        - name: ShoppingListTests
          parallelizable: true
          randomExecutionOrder: true
        - name: ShoppingListUITests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
